<?php
return array(
	'page_access_token' => 'EAADKYgGKeJIBAP6uxENYvSiEBzvZC4QUfeobqXKv43mLqQyuYejKvLGkUqnTtwEz33wAtKf2gXmHpcftkSpLXWBkSyzFDIuW08fZAhfVEydPuF2SqpBW7ZCMp6vuSnxE2OAVHGyY0EjeEAot91VPZA3mQj1jwZBZABfvaILg3CWQZDZD'
);